/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bar.gltf --tranform 
Author: rkmorello (https://sketchfab.com/rkmorello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/billboard-lowpoly-baadeaf2bab344a4a909f6d3a19375b7
Title: Billboard - Lowpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bar.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.176, 19.511, -6.904]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.073, 0.465, 0.073]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Light} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Black} position={[-0.55, 11.67, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.895, 0.077, 9.255]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.009']} position={[-0.467, 15.135, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.21, 1, 0.431]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} position={[1.383, 1.058, 9.084]} />
    </group>
  )
}

useGLTF.preload('/bar.gltf')
