/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 moniteur.gltf --tranform 
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultrawide-monitor-f84d24b6df3648d884fd9be9c8007dd4
Title: Ultrawide Monitor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/moniteur.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -0.001, Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group rotation={[0, 0, Math.PI / 2]} scale={[19.412, 536.206, 242.198]}>
            <mesh geometry={nodes.Ultrawide_Monitor_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Ultrawide_Monitor_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Ultrawide_Monitor_Body_0_1.geometry} material={materials.Body} />
            <mesh geometry={nodes.Ultrawide_Monitor_Lights_0.geometry} material={materials.Lights} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/moniteur.gltf')
